# -*- coding: utf-8 -*-
"""Submit the ontology to the OOPS! pitfall scanner, and compare the result with a baseline.

    python dev_tools/oops_check.py                    # compare against the baseline
    python dev_tools/oops_check.py --write-baseline   # record the current result
    python dev_tools/oops_check.py --check            # CI: exit 1 on any difference
    python dev_tools/oops_check.py -v                 # list every affected element

OOPS! (oops.linkeddata.es) evaluates an ontology against a catalogue of modelling pitfalls.
It was run by hand during development and the paper reports what it found; this runs the
same scan over its REST interface so the report is a fact about the current version rather
than a memory of an old one.

Why a baseline rather than "no pitfalls": several findings are correct and are not going to
be fixed. P34 names the SWRL vocabulary, which Protege writes untyped and which is not
OntoGSN's to declare. P11 names two schema.org properties, and putting a domain on somebody
else's term would be worse than the pitfall. The useful question is not "are there
findings?" but "did the findings change?", which is what a recorded baseline answers.

Two things are deliberately normalised before submitting.

The ontology node is rewritten as a typed <owl:Ontology> element. rdflib's RDF/XML writer
emits it as an <rdf:Description> with an rdf:type child, which is the same graph and which
OOPS! does not recognise: submitted as generated, it reports P39 (critical, "no ontology URI
declared") and P38 ("no owl:Ontology tag") against an ontology that declares both. Both
disappear once the element is typed. Fixing serializations/build.py instead would work
equally well and would change a published artefact, so the normalisation lives here.

The service is asked about content, not about a URI. w3id.org resolves to the copy on the
main branch, which is not what a person is about to commit.

The network is not a gate. A scan that cannot reach the service reports SKIPPED and exits 0:
OOPS! being down is not a defect in the ontology, and it is the only check in this
repository that depends on somebody else's server being up.
"""
import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ONTOLOGY_RDF = os.path.join(REPO, "serializations", "ontogsn.rdf")
BASELINE = os.path.join(REPO, "dev_tools", "testdata", "oops_baseline.txt")

ENDPOINT = "https://oops.linkeddata.es/rest"
TIMEOUT = 300

OOPS_NS = "http://oops.linkeddata.es/def#"
ONTOLOGY_IRI = "https://w3id.org/OntoGSN/ontology"
OWL_ONTOLOGY = "http://www.w3.org/2002/07/owl#Ontology"

LEVEL_ORDER = {"Critical": 0, "Important": 1, "Minor": 2}

HEADER = """# Generated by dev_tools/oops_check.py. Do not edit by hand.
#
# What OOPS! (oops.linkeddata.es) reports about serializations/ontogsn.rdf. Not expected to
# be empty - several of these are correct and deliberate, and the script's docstring says
# which. A new line here is a regression; a line that disappears is a fix, and both want
# the baseline rewritten deliberately.
#
# Elements are listed for a pitfall that names four or fewer, because those are the ones
# worth diffing. Run with -v to see them all.
"""

MANY = 4


def skip(reason):
    print(f"SKIPPED: {reason}")
    sys.exit(0)


def shorten(iri):
    return iri.rsplit("#", 1)[-1] if "#" in iri else iri.rsplit("/", 1)[-1] or iri


def normalised_ontology():
    """The committed RDF/XML with the ontology node written as a typed owl:Ontology element.

    Same graph, different syntax. See the docstring for why the difference matters to OOPS!.
    """
    with open(ONTOLOGY_RDF, encoding="utf-8") as fh:
        text = fh.read()
    pattern = re.compile(
        rf'<rdf:Description rdf:about="{re.escape(ONTOLOGY_IRI)}">(.*?)</rdf:Description>',
        re.S)

    def retype(match):
        body = match.group(1).replace(
            f'<rdf:type rdf:resource="{OWL_ONTOLOGY}" />', "")
        return f'<owl:Ontology rdf:about="{ONTOLOGY_IRI}">{body}</owl:Ontology>'

    normalised, count = pattern.subn(retype, text, count=1)
    if count != 1:
        print(f"note: could not find the ontology node in {os.path.basename(ONTOLOGY_RDF)}; "
              "submitting it unchanged, which may add spurious P38/P39 findings")
    return normalised


def scan(content):
    try:
        import requests
    except ImportError:
        skip("requests is not installed - pip install -r dev_tools/requirements.txt")
    envelope = ('<?xml version="1.0" encoding="UTF-8"?>\n<OOPSRequest>\n'
                '  <OntologyURI></OntologyURI>\n'
                f'  <OntologyContent><![CDATA[{content}]]></OntologyContent>\n'
                '  <Pitfalls></Pitfalls>\n'
                '  <OutputFormat>RDF/XML</OutputFormat>\n</OOPSRequest>')
    try:
        response = requests.post(ENDPOINT, data=envelope.encode("utf-8"),
                                 headers={"Content-Type": "application/xml"},
                                 timeout=TIMEOUT)
    except Exception as error:
        skip(f"could not reach {ENDPOINT} ({type(error).__name__})")
    if response.status_code != 200:
        skip(f"{ENDPOINT} answered HTTP {response.status_code}")
    return response.text


def findings(rdf_text, verbose):
    from rdflib import Graph, Namespace
    oops = Namespace(OOPS_NS)
    graph = Graph()
    graph.parse(data=rdf_text, format="xml")

    rows = []
    subjects = set(graph.subjects(oops.hasCode, None)) | set(graph.subjects(oops.hasName, None))
    for subject in subjects:
        code = graph.value(subject, oops.hasCode)
        name = graph.value(subject, oops.hasName)
        level = str(graph.value(subject, oops.hasImportanceLevel) or "-")
        elements = sorted(shorten(str(o)) for o in graph.objects(subject, oops.hasAffectedElement))
        declared = graph.value(subject, oops.hasNumberAffectedElements)
        count = int(str(declared)) if declared is not None else len(elements)
        rows.append({"code": str(code) if code else str(name),
                     "name": str(name) if name else "",
                     "level": level, "count": count, "elements": elements})

    rows.sort(key=lambda r: (LEVEL_ORDER.get(r["level"], 3), r["code"]))

    lines = []
    for row in rows:
        lines.append(f'{row["code"]}  {row["level"]}  n={row["count"]}  {row["name"]}')
        if row["elements"] and (verbose or len(row["elements"]) <= MANY):
            for element in row["elements"]:
                lines.append(f'    {element}')
    return lines


def read_baseline():
    if not os.path.exists(BASELINE):
        return None
    with open(BASELINE, encoding="utf-8") as fh:
        return [line.rstrip("\n") for line in fh
                if line.strip() and not line.startswith("#")]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-baseline", action="store_true",
                        help="record the current result as the expected one")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the result differs from the baseline")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="list every affected element, not only the short lists")
    args = parser.parse_args()

    # -v lists elements the baseline does not record, so the two cannot be combined
    if args.write_baseline and args.verbose:
        raise SystemExit("--write-baseline records the short listing; run it without -v")

    lines = findings(scan(normalised_ontology()), args.verbose)
    print("\n".join(lines))

    if args.write_baseline:
        with open(BASELINE, "w", encoding="utf-8") as fh:
            fh.write(HEADER + "\n" + "\n".join(lines) + "\n")
        print(f"\nbaseline written to {os.path.relpath(BASELINE, REPO)}")
        return

    expected = read_baseline()
    if expected is None:
        print(f"\nno baseline at {os.path.relpath(BASELINE, REPO)} - "
              "run with --write-baseline to record this result")
        sys.exit(1 if args.check else 0)

    if args.verbose:
        print("\n(-v lists more than the baseline records; not comparing)")
        return

    if lines == expected:
        print("\nmatches the recorded baseline")
        return

    print("\nDIFFERS from the recorded baseline")
    for line in [line for line in lines if line not in expected]:
        print(f"  new:  {line}")
    for line in [line for line in expected if line not in lines]:
        print(f"  gone: {line}")
    print("\nIf the change is intended, re-record it:"
          "\n    python dev_tools/oops_check.py --write-baseline")
    sys.exit(1 if args.check else 0)


if __name__ == "__main__":
    main()
