# -*- coding: utf-8 -*-
"""Put the ontology and the fixtures through an OWL-DL reasoner, and compare with a baseline.

    python dev_tools/reasoner_check.py                    # compare against the baseline
    python dev_tools/reasoner_check.py --write-baseline   # record the current result
    python dev_tools/reasoner_check.py --check            # CI: exit 1 on any difference
    python dev_tools/reasoner_check.py -v                 # show the reasoner's own output

SHACL answers whether data matches the constraints the ontology's axioms imply. It does not
answer whether those axioms can all hold at once, and it cannot: a shape is checked against
a graph, an inconsistency is a property of the axioms themselves. That is what this asks.

Four graphs are checked, and one of them is expected to fail:

    ontology alone            consistent, and no class unsatisfiable
    + the well-formed case    consistent - a real assurance case has to reason
    + one trigger per rule    consistent
    + the whole fixture       INCONSISTENT, and the reason is known

The last one is why this records a baseline instead of asserting "consistent". The tail of
example_case.ttl is deliberately malformed so the diagnostic queries have something to find,
and it closes a support cycle. gsn:supportedBy is asymmetric and irreflexive, so that cycle
is not merely bad practice - it is an OWL contradiction, and a reasoner is right to reject
it. "Consistent" is the wrong expectation for that graph; "inconsistent, for this reason,
and nothing else changed" is the right one.

The well-formed graph is the same file cut at the banner announcing the malformed section,
so the split follows the fixture rather than a line number that would rot.

Pellet is the copy owlready2 bundles - nothing to install, but it needs a JVM on the PATH.
With no JVM, or no owlready2, this reports SKIPPED and exits 0. An absent reasoner is not a
defective ontology, and a machine that never had Java should not turn CI red.

One limitation is recorded rather than hidden. This Pellet has no swrlx:makeOWLThing
builtin, so every rule that mints an individual is dropped with a warning - nine of them at
1.2.4. Those rules are exactly what the SWRLAPI's Drools engine covered in Protege and what
queries/rules/ executes here, so the gap is real and worth seeing. The baseline records
which rules were dropped; a rule joining or leaving that list is a finding.
"""
import argparse
import glob
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ONTOLOGY = os.path.join(REPO, "serializations", "ontogsn.ttl")
TESTDATA = os.path.join(REPO, "dev_tools", "testdata")
FIXTURE = os.path.join(TESTDATA, "example_case.ttl")
RULE_FIXTURE = os.path.join(TESTDATA, "rule_cases.ttl")
BASELINE = os.path.join(TESTDATA, "reasoner_baseline.txt")

# the banner the fixture puts in front of the section that is wrong on purpose
MALFORMED_MARKER = "Deliberately malformed"

JAVA_MEMORY = "2000"

SCENARIOS = [
    ("ontology", "serializations/ontogsn.ttl alone - the TBox"),
    ("well-formed case", "the ontology and example_case.ttl up to the malformed section"),
    ("rule triggers", "the ontology and rule_cases.ttl"),
    ("whole fixture", "the ontology and all of example_case.ttl, malformed tail included"),
]

IGNORED_RULE_RE = re.compile(r"Ignoring rule Rule\((\w+)[^)]*\)[^:]*: No builtin for (\S+)")

HEADER = """# Generated by dev_tools/reasoner_check.py. Do not edit by hand.
#
# What Pellet concludes about the ontology and the fixtures. One graph is expected to be
# INCONSISTENT: the tail of example_case.ttl is malformed on purpose and closes a
# gsn:supportedBy cycle, which contradicts that property's asymmetry. The expectation is
# not "consistent" but "exactly this, and nothing new".
#
# The ignored-rule lines are a limitation of this reasoner, not a defect in the ontology:
# the bundled Pellet has no swrlx:makeOWLThing builtin, so rules that mint an individual
# are dropped. queries/rules/ executes them instead.
"""


def skip(reason):
    print(f"SKIPPED: {reason}")
    sys.exit(0)


def pellet_classpath():
    """The classpath of the Pellet owlready2 ships.

    owlready2 exposes it under a private name, so fall back to globbing the jars it
    installs rather than depending on that name staying where it is.
    """
    try:
        import owlready2
    except ImportError:
        skip("owlready2 is not installed - pip install -r dev_tools/requirements.txt")
    try:
        from owlready2.reasoning import _PELLET_CLASSPATH
        return _PELLET_CLASSPATH
    except ImportError:
        jars = glob.glob(os.path.join(os.path.dirname(owlready2.__file__), "pellet", "*.jar"))
        if not jars:
            skip("owlready2 is installed but ships no Pellet jars")
        return os.pathsep.join(jars)


def java_exe():
    try:
        import owlready2
        candidate = owlready2.JAVA_EXE
    except ImportError:
        candidate = "java"
    if os.path.isfile(candidate):
        return candidate
    found = shutil.which(candidate)
    if not found:
        skip("no JVM on the PATH - the reasoner needs one, every other check does not")
    return found


def well_formed_text():
    """example_case.ttl with the deliberately malformed section removed."""
    with open(FIXTURE, encoding="utf-8") as fh:
        text = fh.read()
    if MALFORMED_MARKER not in text:
        raise SystemExit(f"{FIXTURE} no longer contains the {MALFORMED_MARKER!r} banner, "
                         "which is where this script cuts it")
    lines = text.split(MALFORMED_MARKER)[0].splitlines()
    # drop the banner's own rule of hashes, which the split left dangling
    while lines and set(lines[-1].strip()) <= set("#"):
        lines.pop()
    return "\n".join(lines) + "\n"


def graph_for(scenario):
    from rdflib import Graph
    graph = Graph()
    graph.parse(ONTOLOGY, format="turtle")
    if scenario == "well-formed case":
        graph.parse(data=well_formed_text(), format="turtle")
    elif scenario == "rule triggers":
        graph.parse(RULE_FIXTURE, format="turtle")
    elif scenario == "whole fixture":
        graph.parse(FIXTURE, format="turtle")
    return graph


def run_pellet(subcommand, path, classpath, java):
    """-> (stdout, stderr). Pellet exits 0 whatever it concludes, so read the text."""
    command = [java, f"-Xmx{JAVA_MEMORY}M", "-cp", classpath, "pellet.Pellet", subcommand,
               "--loader", "Jena", "--input-format", "N-Triples", "--ignore-imports", path]
    result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8",
                            errors="replace")
    return result.stdout or "", result.stderr or ""


def ignored_rules(stderr):
    """The rules the reasoner dropped, and the builtin it lacked, as sorted lines."""
    return sorted({f"{name} - no builtin {builtin.rsplit('#', 1)[-1]}"
                   for name, builtin in IGNORED_RULE_RE.findall(stderr)})


def verdict(stdout):
    match = re.search(r"^Consistent:\s*(Yes|No)\s*$", stdout, re.M)
    if not match:
        return "unknown", ""
    if match.group(1) == "Yes":
        return "yes", ""
    reason = re.search(r"^Reason:\s*(.+?)\s*$", stdout, re.M)
    return "no", reason.group(1) if reason else "none given"


def unsatisfiable(stdout):
    if "Found no unsatisfiable concepts" in stdout:
        return []
    return sorted(line.strip() for line in stdout.splitlines()
                  if line.strip() and not line.startswith(("Found", "Reading", "Loading")))


def evaluate(verbose):
    classpath = pellet_classpath()
    java = java_exe()
    report = []
    dropped = {}
    workdir = tempfile.mkdtemp(prefix="ontogsn-reasoner-")
    try:
        for scenario, description in SCENARIOS:
            graph = graph_for(scenario)
            path = os.path.join(workdir, scenario.replace(" ", "_") + ".nt")
            graph.serialize(destination=path, format="nt", encoding="utf-8")

            stdout, stderr = run_pellet("consistency", path, classpath, java)
            state, reason = verdict(stdout)
            report.append(f"## {scenario} ({len(graph)} triples)")
            report.append(f"## {description}")
            report.append(f"consistent: {state}")
            if state == "no":
                report.append(f"reason: {reason}")
            elif state == "unknown":
                report.append("the reasoner printed no verdict; run with -v to see why")

            # Unsatisfiability is a property of the TBox, so asking once is enough - and
            # asking at all is meaningless once a graph is already inconsistent.
            if scenario == "ontology":
                unsat_out, _ = run_pellet("unsat", path, classpath, java)
                found = unsatisfiable(unsat_out)
                report.append("unsatisfiable classes: " + (", ".join(found) if found else "none"))
            report.append("")

            # The dropped rules depend on the rule set, not on the data, so they are
            # reported once. A scenario that drops a different set is worth seeing, and
            # gets its own block below.
            dropped[scenario] = ignored_rules(stderr)

            if verbose:
                print(f"----- {scenario}: pellet consistency -----")
                print(stdout.strip() or "(no output)")
                print(stderr.strip() or "(no warnings)")
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    common = set.intersection(*(set(v) for v in dropped.values())) if dropped else set()
    report.append("## rules this reasoner dropped, in every graph above")
    report.append("## not a defect in the ontology - see the header")
    for line in sorted(common):
        report.append(f"ignored rule: {line}")
    if not common:
        report.append("none")
    for scenario, lines in dropped.items():
        extra = sorted(set(lines) - common)
        if extra:
            report.append("")
            report.append(f"## dropped only in: {scenario}")
            for line in extra:
                report.append(f"ignored rule: {line}")
    return report


def read_baseline():
    if not os.path.exists(BASELINE):
        return None
    with open(BASELINE, encoding="utf-8") as fh:
        return [line.rstrip("\n") for line in fh
                if line.startswith("## ") or not line.startswith("#")]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-baseline", action="store_true",
                        help="record the current result as the expected one")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the result differs from the baseline")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="show the reasoner's own output")
    args = parser.parse_args()

    report = evaluate(args.verbose)
    rendered = "\n".join(report).rstrip("\n")

    if args.write_baseline:
        with open(BASELINE, "w", encoding="utf-8") as fh:
            fh.write(HEADER + "\n" + rendered + "\n")
        print(rendered)
        print(f"\nbaseline written to {os.path.relpath(BASELINE, REPO)}")
        return

    print(rendered)
    expected = read_baseline()
    if expected is None:
        print(f"\nno baseline at {os.path.relpath(BASELINE, REPO)} - "
              "run with --write-baseline to record this result")
        sys.exit(1 if args.check else 0)

    # compare on content, ignoring the blank lines that only lay the report out
    actual = [line for line in report if line.strip()]
    wanted = [line for line in expected if line.strip()]
    if actual == wanted:
        print("\nmatches the recorded baseline")
        return

    print("\nDIFFERS from the recorded baseline")
    for line in [line for line in actual if line not in wanted]:
        print(f"  new:  {line}")
    for line in [line for line in wanted if line not in actual]:
        print(f"  gone: {line}")
    print("\nIf the change is intended, re-record it:"
          "\n    python dev_tools/reasoner_check.py --write-baseline")
    sys.exit(1 if args.check else 0)


if __name__ == "__main__":
    main()
