PREFIX gsn:  <https://w3id.org/ontogsn/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

SELECT ?sol WHERE {
  ?sol a gsn:Solution .
  FILTER NOT EXISTS { ?sol gsn:refersTo ?artifact . }
}
