PREFIX gsn: <https://w3id.org/ontogsn/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX case: <https://w3id.org/ontogsn/my_assurance_case#>

SELECT DISTINCT ?goal
WHERE {
  ?goal gsn:supportedBy+ case:Sn1_2_1_1 .
  ?goal rdf:type gsn:Goal .
}